name: Hello World

on: workflow_dispatch

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World this is the first code which is written by me"
